
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const PROPERTY_LOADING = "PROPERTY_LOADING";
export const PROPERTY_ERROR = "PROPERTY_ERROR";
export const ADD_PROPERTIES = "ADD_PROPERTIES";
export const ADD_PROPERTY = "ADD_PROPERTY";