
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const PROPERTY_LOADING = "PROPERTY_LOADING";
export const PROPERTY_ERROR = "PROPERTY_ERROR";
export const ADD_PROPERTIES = "ADD_PROPERTIES";
export const ADD_PROPERTY = "ADD_PROPERTY";

export const ADD_RECENT = "ADD_RECENT";
export const RECENT_LOADING = "RECENT_LOADING";
export const RECENT_FAILED = "RECENT_FAILED";

export const ADD_MY_PROPERTIES = "ADD_MY_PROPERTIES";
export const REMOVE_MY_PROPERTY = "REMOVE_MY_PROPERTY";
export const MY_PROPERTIES_LOADING = "MY_PROPERTIES_LOADING";
export const MY_PROPERTIES_FAILED = "MY_PROPERTIES_FAILED";
